# Generated by Django 4.0.2 on 2022-02-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='certificate',
            field=models.FileField(upload_to='apps/data/certs/'),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
