# Generated by Django 4.0.2 on 2022-02-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_company_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('razon_social', models.CharField(max_length=60)),
                ('certificate', models.FileField(upload_to='api_sii/data/certificados/clients')),
                ('certificate_pass', models.CharField(max_length=60)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='certificate',
            field=models.FileField(upload_to='api_sii/data/certificados/company'),
        ),
    ]
