# Generated by Django 4.0.2 on 2022-02-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cliente_alter_company_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='state',
            new_name='Estado',
        ),
    ]
