# Generated by Django 4.0.2 on 2022-03-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_errors_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Errors',
        ),
    ]
