# Generated by Django 4.0.2 on 2022-03-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_errors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.CharField(max_length=25)),
                ('msg', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=25)),
            ],
        ),
    ]
