# Generated by Django 4.0.3 on 2022-03-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_cliente_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='certificate',
            field=models.FileField(upload_to='api_sii/data/certificados/clientes'),
        ),
    ]
