# Generated by Django 4.0.2 on 2022-03-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libredte', '0002_alter_log_msg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='ClienteDTE',
        ),
        migrations.RenameModel(
            old_name='Log',
            new_name='LogDTE',
        ),
    ]
