# Generated by Django 4.0.3 on 2022-03-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libredte', '0004_alter_clientedte_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientedte',
            name='certificate',
            field=models.FileField(upload_to='api_sii/api/data/certificados/clientsDTE'),
        ),
    ]
